### ISSUE TITLE
Sun vector

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#12]
Looks like there is no function for setting sun vector, and using dream.sun = vec3(x, y, z) does not allow to change the moving direction of sun. And the same thing for moon can be useful too. And an interface for adding additional moons and other orbital satellites.

**Comment by Luke100000** [comment]
The sun and moon cycle relies on its inbuilt time and sun angle system. I cant recall exactly why I did this.
`dream.sun_offset` is the angle, where 0 is equator and 1 the poles.
`dream:setDaytime(time)` sets vector, color, moon phase, etc automatically based on this
`dream:resetLight()` applies changes to the sun object.
If you want a custom sky sphere you can change it in dream/jobs.lua:296 and I am working on a proper way to supply a custom one without changing engine code.

**Comment by Luke100000** [comment]
Added, `dream:setSunDir(vec3)` is capable of setting directly and the sun is rendered at the correct position. Moon is currently always opposite, I am considering multi-planets feature once actually needed by someone :)
