### ISSUE TITLE
hangs on pressing some keys

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#13]
3DreamEngine does not react on pressing keys (via love2d of course) after pressing Shift and some other keys (usually functional and modificators). Letters and arrows work fine. UP: probably my mistake, I'll check this carefully.

**Comment by Luke100000** [comment]
I left as few debug buttons in it which needs to be disabled ("-", ".", ",") but none if these should cause a freeze. I will investigate this issue.
