### ISSUE TITLE
Question or feature request about dithering at the distance

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#15]
Is it possible to activate dithering (like semi-transparent pixels has) for far objects? To allow their slow, step-by-step appearing at the distance of drawing?

**Comment by Luke100000** [comment]
It is technically possible but required minor modifications. I will add it together with LoD since this feature depends on distance dither too.

**Comment by Luke100000** [comment]
Done. Use dream.alphaBlendMode = "dither" (or let it unchanged for transparent fade out) and set the color (alpha channel) with l.g.setColor() before the draw call. Currently LoDs do not fade but I want to add this too.
