### ISSUE TITLE
dream.deferred_lighting = true artifacts

### ISSUE THREAD

**Issue by seanpringle** [3dreamengine/3DreamEngine#16]
I know the [readme mentions](https://github.com/3dreamengine/3DreamEngine#deferred-rendering) possible lighting distortion when `dream.deferred_lighting = true`. I'm curious if the white edge atrifacts on my shipping container below are an example of this, or if I need to debug my models further? The artifacts don't appear with normal non-deferred lighting.

The model meshes have small rounded bevels on all edges. If I make the bevel radius larger the artifacts move around a bit, but still appear.

![3DreamEngine-artifacts](https://user-images.githubusercontent.com/120825/85492970-64373a00-b619-11ea-9b3a-3731b76bac15.png)

In case it's relevant, the code that sets up dream:

```lua
dream.msaa = 16
dream.bloom_enabled = false
dream.secondPass = true
dream.deferred_lighting = true
dream.shadow_factor = 4
dream.shadow_resolution = dream.shadow_resolution*2
dream.shadow_cube_resolution = dream.shadow_cube_resolution*2
dream.shadow_distance = 10
dream.sky_enabled = false
dream.sun = vec3(-0.5,1,0)
dream.sun_color = vec3(2.0, 2.0, 2.0)
dream.sun_ambient = vec3(0.5, 0.5, 0.5)

dream.cam.fov = 45
dream.cam.eye = vec3(0,15,5)
dream.cam.target = vec3(0,0,0)

dream:init()

container = dream:loadObject("shipping-container", {splitMaterials = true})
platform = dream:loadObject("platform", {splitMaterials = true})

--- [snip ui test stuff; mouse/camera math]

function love.draw()
  dream:resetLight()
  dream:prepare()
  dream.cam:reset()
  dream.cam.transform = dream:lookAt(dream.cam.eye, dream.cam.target)
  dream:draw(container, 0, 1, 0)
  dream:draw(platform, 0, -0.5, 0)
  dream:present()
  ui:draw()
end
```

Unrelated: This engine is great! Thanks for the effort :-)

**Comment by Luke100000** [comment]
Your code looks fine to me. Do all models have these edges? If I have some spare time I will try additional GPUs to see if I can reconstruct this problem myself. Deferred lighting is only useful for more than ~8 light sources, for the experimental screen space reflections and smooth shadows (which might be available for forward shading soon).
Thanks for the kind words!

**Comment by seanpringle** [comment]
So far all models show the edges, but then I'm generating them from the same Blender pipeline... so perhaps not a good sample. I'll try others. Also ftr no textures are in use. Just .obj meshes with plain color materials, mostly specular metallic.

Platform is Ubuntu 20.04, GPU is Nvidia GTX 1660 with stock driver 440.64.

**Comment by seanpringle** [comment]
Can't attach them, so stripped down sample code and models in question: https://github.com/seanpringle/3DreamEngine16

**Comment by Luke100000** [comment]
> 
> 
> Can't attach them, so stripped down sample code and models in question: https://github.com/seanpringle/3DreamEngine16

Thanks a lot for the sample code. The error happens on my PC too, not as visible as in the screenshot but present.

**Comment by Luke100000** [comment]
I have found the location but not the cause of the error.
You can avoid it by using Phong shading while I try to fix it.
`dream.lighting_engine = "Phong"`
I will most likely set the default shading to Phong anyways since it is more common.

**Comment by Luke100000** [comment]
issue #23 was the same error and it has been fixed. At least for me, please reopen the issue if not.
