### ISSUE TITLE
Getting collider by screen coordinates (from mouse cursor): really important

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#18]
Any plans for adding 3d buttons  to make clicking on 3d scene objects available?

**Comment by Luke100000** [comment]
Not specifically buttons but the in progress collision library (3Dream/collision.lua) has a rather slow but accurate mesh collision. You can test against a ray.

Or the 3DreamCreator (probably going to be removed due its lack of usability) has this function in its utils.lua: `utils.selectTriangulationMesh(mesh, x, y, transform)`. It takes as input a mesh, an absolute screen pixel and a transformation matrix for the mesh and tests if it is selected. If the 3DreamCreator gets removed I will preserve and improve this function.

I will mark this issue as resolved once there is a proper easy to use function for this.

**Comment by thisnickwasfree** [comment]
>probably going to be removed due its lack of usability

Removed.
Anyway, could you add code and docs for selectTriangulationMesh and RayCast/MeshCollision functions?

Trying to write an old-school rpg game, using 3dreamengine, so this functionality could be extremely useful.

**Comment by thisnickwasfree** [comment]
One more moment. The function of selecting mesh by click should understand that all meshes can be instances of one. For example, all spearmen on the map has the same mesh, which added to their classes as a variable. So, they should differs from each other somehow, I think…

**Comment by thisnickwasfree** [comment]
Sorry for hurrying up but a possibility to get mesh by clicking at the screen is really needed.
I can find myself some circuitous ways to solve this, but i can get an "architecture of load-carrying crutch" as a result.
So, could you try to update code and documentation about this in nearest time?
The function is really useful for gamedev.

**Comment by Luke100000** [comment]
> 
> 
> Sorry for hurrying up but a possibility to get mesh by clicking at the screen is really needed.
> I can find myself some circuitous ways to solve this, but i can get an "architecture of load-carrying crutch" as a result.
> So, could you try to update code and documentation about this in nearest time?
> The function is really useful for gamedev.

Ok, I looked into it and made a small demo in the tavern demo. Press L and it will print the object you are looking at.
Documentation will follow soon.
The performance is miserable. Accurate detection, but slow, especially with larger meshes as in the tavern demo. I will add further performance optimizations, but they should not change the interface.
Here a short use case based on what you need, I think:
```
collision = require("3DreamEngine/collision") --load lib
collider = collision:newMesh(yourObject) --load a collider from a object, use accelerating structures (group) automatically
collider = collision:newMesh(yourObject.objects.yourSubObject) --load a collider from a subobject
segment = collision:newSegment(vec3 a, vec3 b) --create a segment between a and b, for example camera origin to mouse click direction, or the current camera normal
local hasCollided = collision:collide(a, b) --collide a with b, for example the segment with a mesh
```

**Comment by thisnickwasfree** [comment]
>Here a short use case based on what you need, I think

As I understand, collider is generated from the data, returned by dream:loadObject, right? UP: No.
And here is the first problem: all objects of one type rendered at the scene have the same collider, right? UP: No.
So, that's impossible to differ instances in this case.

UP: Sorry, that's not a problem if we can use coordinates of collision to differ instances from each other.

The second thing.

>create a segment between a and b, for example camera origin to mouse click direction, or the current camera normal

As I understand, to get b-vector, I should take projectional-view matrix of the camera and multiply it to coordinates of mouse cursor. So, at least It would be nice to have method for this.

The third.

>assert(object.faces, "Object has been cleaned up, collision can be reconstructed. Use noCleanup = true argument in object loader!")

This spams all the time, even if all objects in scene are loaded with noCleanup option.
May be, some system objects, like moon or sun are loading without it?

**Comment by Luke100000** [comment]
Forgot to say, colliders can be moved with `collider:moveTo(pos)`, so yes, you can move it for each instance.
Transformations (mat4) are technically possible but have no well defined interface yet.

> As I understand, to get b-vector, I should take projectional-view matrix of the camera and multiply it to coordinates of mouse cursor. So, at least It would be nice to have method for this.
The inverse of the projection matrix, yes. I add a function soon.

> This spams all the time, even if all objects in scene are loaded with noCleanup option.
> May be, some system objects, like moon or sun are loading without it?

I'm not sure how you load the colliders. Why are the sky billboards part of it?
I want to add an alternative which directly uses the mesh data to avoid noCleanup at all. Saves memory and is more reliable. Especially since 3do files are always cleaned and therefore wont work.
If you have to control over the objects then pcall is your friend ^^

**Comment by thisnickwasfree** [comment]
>I'm not sure how you load the colliders. Why are the sky billboards part of it?


That was my only idea about getting  "Use noCleanup" message without visible reasons.

Anyway, a question about getting vector from screen coordinates is still interesting.

UP: transforming feature request.
The way of getting second vector for collision:collide function from coordinates of mouse cursor is needed.

UP: Or getting collision with collider from the screen coordinates — better variant.

**Comment by Luke100000** [comment]
Implemented in the latest commits, see readme docu and Tavern demo (Press K and L, then point on objects).
Feel free to ask further questions here or on the discord.

**Comment by thisnickwasfree** [comment]
Does collision:newMesh(yourObject) takes as an argument what dream:loadObject returns?

I see you use collision:newGroup(). Is it neccesary for working collision  or it needed only for comfortable running over the list of collisions?

For example…

1. I create class of mob.
2. Then I create an exemplar of this class.
3. Create set of meshes with dream:loadObject.
4. And add them to an ex.
5. Create collider like this: local _mob_collider_mesh = dream:loadObject("models/collider", {splitMaterials = false, noCleanup = true}). The model is just a capsule.
UP: 5.5 dream:newMesh(_mob_collider_mesh)
6. Add the collider to ex (later it can be get with mob:GetCollider () written for this).
7. Moving the collider on mob spawn and mobe moving.
8. On mouse click I create segment and getting the collider from the mob.
9. And at this step I'm planning to get information about collision…

Is there any principle errors in this chain?

**Comment by Luke100000** [comment]
Groups are optional, newMesh however will create a group with the actual mesh inside it. Performance reasons. Ignore that, it should not affect you.

Yes, loadObject returns a valid object (only if cleanup is used).
You can put the colliding meshes into the actual mesh file and call the objects "COLLISION_whatever" which should be used for collision. One file and faster, does not require noCleanup. But your current idea works as well. I will add an loader arg to load a file as collisions only to further support this approach.

NewMesh can be slow if using on renderable objects, create it once and reuse it. Optionally use :clone(), if you need several instances at once.

Step 9 would be collision:collide(segment, mob:GetCollider(), true). You have to put the segment in the first arg because of the grouping explained above. True means you are not interested in normal and position, only if it collides.

Yes I think your chain should work fine.

**Comment by thisnickwasfree** [comment]
Well, do not know where to post the link, so posting here:
https://www.youtube.com/watch?v=m-VTd5Tha3o&feature=youtu.be

Just demo atm.
3d part is made with 3dreamengine. Sorry for quality: video was already compressed by capture-soft at my pc and then youtube has added his own compression.

Well, I hope I'll complete this project in a year or two, but anyway thanx for your work. Hope, 3dreamengine will live in progress, becoming better and better with any release.

**Comment by Luke100000** [comment]
> 
> 
> Well, do not know where to post the link, so posting here:
> https://www.youtube.com/watch?v=m-VTd5Tha3o&feature=youtu.be
> 
> Just demo atm.
> 3d part is made with 3dreamengine. Sorry for quality: video was already compressed by capture-soft at my pc and then youtube has added his own compression.
> 
> Well, I hope I'll complete this project in a year or two, but anyway thanx for your work. Hope, 3dreamengine will live in progress, becoming better and better with any release.

Impressive! Thanks for sharing and much luck for your project!
