### ISSUE TITLE
Texture filtering and links to textures

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#20]
Well, loading textures through love-loader now works fine.
But I've noticed one strange thing: pkm and png textures, loaded through love-loader look like they have linear filter accepted ,when I use nearest one. And the «traditional» method (png and mtl) works as it should.

**Comment by Luke100000** [comment]
> 
> 
> Well, loading textures through love-loader now works fine.
> But I've noticed one strange thing: pkm and png textures, loaded through love-loader look like they have linear filter accepted ,when I use nearest one. And the «traditional» method (png and mtl) works as it should.

Strange. Although this setting only affects the internal resource loader, is dream.textures_filter = "nearest"?

Can you print out the current filter modes of your textures? Including the mipmap filter mode?

Also, silly question, but did you specify the default filter mode to nearest before using the love-loader?

**Comment by thisnickwasfree** [comment]
>Can you print out the current filter modes of your textures? Including the mipmap filter mode?
	dream.textures_filter = "nearest";
	dream.textures_mipmaps = false;

>Also, silly question, but did you specify the default filter mode to nearest before using the love-loader?

Hm. love-loader starts before all 3dreamengine components: it should preload all resources first.

**Comment by Luke100000** [comment]
> 
> 
> > Can you print out the current filter modes of your textures? Including the mipmap filter mode?
> > dream.textures_filter = "nearest";
> > dream.textures_mipmaps = false;
> 
> > Also, silly question, but did you specify the default filter mode to nearest before using the love-loader?
> 
> Hm. love-loader starts before all 3dreamengine components: it should preload all resources first.

But did you set the default filter before the love loader?

EDIT: see issue #21 for answer
