### ISSUE TITLE
Instances

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#3]
Is there any way to rotate instance (loaded meshes which are drawn several times) not all together?

**Comment by Luke100000** [comment]
Real instancing is currently not supported, you need to rotate, draw, rotate, draw...

**Comment by thisnickwasfree** [comment]
Oh… Sorry for several questions — planning to make an old-school game with 3d part using your engine, so asking about any unclear moment. But the real instancing would be extremely good anyway.

**Comment by Luke100000** [comment]
No problem, then I will take a look at instancing. But I think you want something different (instancing is just a performance boost). Can you rotate them right before drawing? Do you want to store several transformations? You can create a transformation using mat4(), then replace the objects transformation (object.transform) with this when drawing.

**Comment by thisnickwasfree** [comment]
>But I think you want something different
>Can you rotate them right before drawing?
I can. But when I rotate one instance, I see all of them roatting.

1. I load the mesh with dream:loadObject.
2. I'm parsing the table of the level (created with Tiled editor for example), and inserting links to loaded object to the new table, Objects.
3. In love.draw function I'm reading the Objects table and make dream:draw (link, x, y, z) for any element of the table.
4. I rotate the mesh: loaded_object:rotateY (r)
5. And watching all the copies rotating every update.
Of course I can rotate the mesh before or after drawing — this does not metter.

>You can create a transformation using mat4(), then replace the objects transformation (object.transform) with this when drawing.

Hm. Does this mean I can load one object and then create, for example, four transformation for it using code? I'll check this method…

**Comment by Luke100000** [comment]
ahhh you need to call :reset() before each update. Rotate is relative.

```
object:reset()
object:rotateY(rot)
object:translate(x, y, z)
dream:draw(object)
```

Or, for example if the transformation is static:
```
transform = mat4()
transform:rotateY(rot)
transform:translate(x, y, z)

object.transform = transform
dream:draw(object)
```

**Comment by thisnickwasfree** [comment]
>ahhh you need to call :reset() before each update. Rotate is relative.

Oh, thanx… Looks like this detail make what I needed.
Well, that's not my last question, but anyway thank you for this great library!

**Comment by seanpringle** [comment]
Just another enthusiastic vote for hardware instancing :)

Currently it's possible to tank FPS with many `.draw` calls where `drawInstanced` would help. Maybe simplest to go straight to GLSL 3 and `love_instanceID`?

**Comment by Luke100000** [comment]
> 
> 
> Just another enthusiastic vote for hardware instancing :)
> 
> Currently it's possible to tank FPS with many `.draw` calls where `drawInstanced` would help. Maybe simplest to go straight to GLSL 3 and `love_instanceID`?

I have performed a few benchmarks in regards of drawInstanced. Thanks to love2ds new batching system (I assume its the cause) instances no longer grant a performance boost.
EDIT: l.g.getStats() says no batching. Then I am not sure why I do not see a benefit. I will look further into this, but for now I will skip instancing.

For the currently quite slow particles I probably will use instancing, but for most objects I see no benefits in using it.

I am currently improving the current ordering and grouping function of the 3DreamEngine to reduce draw call overhead, batch together meshes to help love2ds batching (and allow additional neat features like LoDs, alpha blending, frustum check, ...)

**Comment by Luke100000** [comment]
Instancing has been added, documentation still missing tho
