### ISSUE TITLE
some exemples seems broken

### ISSUE THREAD

**Issue by giovifav** [3dreamengine/3DreamEngine#33]
Hi, 
i'm looking into the exemples and some of them seems broken:
In lamborghini example ,  knight example, lowpolygame example, monkey example, and particle system example all models are rendered black like there wasn't a light.
it is my fault ?

**Comment by Luke100000** [comment]
> 
> 
> Hi,
> i'm looking into the exemples and some of them seems broken:
> In lamborghini example , knight example, lowpolygame example, monkey example, and particle system example all models are rendered black like there wasn't a light.
> it is my fault ?

Shaders are annoying. They work on some systems, but may fail on others. Thanks for reporting, I will run it on other GPUs and try to find all hardware specific bugs.

**Comment by giovifav** [comment]
my laptop specs:
`
Kernel: 5.4.0-42-generic x86_64 bits: 64 
  Desktop: Gnome 3.36.3 Distro: Ubuntu 20.04.1 LTS (Focal Fossa) 
Machine:
  Type: Laptop System: HP product: HP Laptop 15-db0xxx 
  v: Type1ProductConfigId serial: <superuser/root required> 
  Mobo: HP model: 84AF v: 86.20 serial: <superuser/root required> 
  UEFI: Insyde v: F.11 date: 08/20/2018 
Battery:
  ID-1: BAT1 charge: 12.2 Wh condition: 37.4/41.0 Wh (91%) 
CPU:
  Topology: Dual Core model: AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx 
  bits: 64 type: MT MCP L2 cache: 1024 KiB 
  Speed: 1369 MHz min/max: 1600/2500 MHz Core speeds (MHz): 1: 1423 2: 1428 
  3: 1368 4: 1380 
Graphics:
  Device-1: AMD Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] 
  driver: amdgpu v: kernel 
  Display: x11 server: X.Org 1.20.8 driver: ati,fbdev 
  unloaded: modesetting,radeon,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: AMD RAVEN (DRM 3.35.0 5.4.0-42-generic LLVM 10.0.0) 
  v: 4.6 Mesa 20.0.8 
`

a few month ago while I'm looking at your project had the same problem but back then i figure out a solution.
i lost that files but , if i remember correctly, i added some light ( or set a global light)   into the scene and the problem disappear.

**Comment by giovifav** [comment]
also the minimal example in readme dosn't work in my system.

**Comment by Luke100000** [comment]
Thanks for the information.
Sadly I found no new errors (canvas mipmaps still fail on Intel) on my Intel UHD 620.
Integrated GPUs are usually rather picky, so I use the Intel to validate shaders, however it seems we have a new problem here, especially since it is not a crash.
I want to run my engine on mobile phones, those are the pickiest one available. Once I am successful I will come back to this topic, maybe its fixed then.
If you have time, please try this: `init.lua:14`, set `_DEBUGMODE` to true. `shaders.lua:8` set `testForOpenES` to true. Run it. It will validate the shaders on the lowest level possible and prints any errors in the console.
Does any example work?

**Comment by Luke100000** [comment]
> a few month ago while I'm looking at your project had the same problem but back then i figure out a solution.
> i lost that files but , if i remember correctly, i added some light ( or set a global light) into the scene and the problem disappear.

Cubemaps maybe? `dream.sky_as_reflection = false` and then the monkey example would run without cubemaps and use a global light instead. `dream.sun_shadow` disables the sun shadow too.

**Comment by giovifav** [comment]
Working examples: 
AlphaBlending is working but only when choose a blend mode otherwise all the screen is black.
Tavern is working but take a while to load on my system and the fps is under 26 ( maybe is my a fault of my cheap pc)
Blacksmith seems run fine.

running the Lamborghini example with debug output this:
-------------------------------------------------------------------------

SHADER ERROR
3DreamEngine/shaders/blur_cube.glsl
Error validating pixel shader:

ERROR: 0:13: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 1 compilation errors.  No code generated.
stack traceback:
	3DreamEngine/shader.lua:23: in function 'newShader'
	3DreamEngine/shader.lua:77: in main chunk
	[C]: in function 'require'
	3DreamEngine/init.lua:31: in main chunk
	[C]: in function 'require'
	examples/Lamborghini/main.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:74: in function 'draw'
	[string "boot.lua"]:618: in function <[string "boot.lua"]:594>
	[C]: in function 'xpcall'
	[string "boot.lua"]:802: in function <[string "boot.lua"]:769>


shader simple is not designed for mesh type textured!
shader simple is not designed for mesh type textured!

running first person example output this:
------------------------------------------------------

SHADER ERROR
3DreamEngine/shaders/blur_cube.glsl
Error validating pixel shader:

ERROR: 0:13: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 1 compilation errors.  No code generated.



stack traceback:
	3DreamEngine/shader.lua:23: in function 'newShader'
	3DreamEngine/shader.lua:77: in main chunk
	[C]: in function 'require'
	3DreamEngine/init.lua:31: in main chunk
	[C]: in function 'require'
	examples/firstpersongame/main.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:74: in function 'draw'
	[string "boot.lua"]:618: in function <[string "boot.lua"]:594>
	[C]: in function 'xpcall'
	[string "boot.lua"]:802: in function <[string "boot.lua"]:769>


shader simple is not designed for mesh type textured!
shader simple is not designed for mesh type textured!
material: 10286 particle-faces
material: 3384 particle-faces
material: 0 particle-faces
material: 0 particle-faces

running voxel/knight output:
-------------------------------------


SHADER ERROR
3DreamEngine/shaders/blur_cube.glsl
Error validating pixel shader:

ERROR: 0:13: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 1 compilation errors.  No code generated.



stack traceback:
	3DreamEngine/shader.lua:23: in function 'newShader'
	3DreamEngine/shader.lua:77: in main chunk
	[C]: in function 'require'
	3DreamEngine/init.lua:31: in main chunk
	[C]: in function 'require'
	examples/knight/main.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:74: in function 'draw'
	[string "boot.lua"]:618: in function <[string "boot.lua"]:594>
	[C]: in function 'xpcall'
	[string "boot.lua"]:802: in function <[string "boot.lua"]:769>


shader simple is not designed for mesh type textured!
shader simple is not designed for mesh type textured!
transform	0	1	0	4484
group	1	6
transform	2	3	22	4572
shape	3
transform	4	5	17	4683
shape	5
transform	6	7	17	4789
shape	7
transform	8	9	22	4895
shape	9
transform	10	11	23	5007
shape	11
transform	12	13	23	5118
shape	13
gen	foot left	-18	-24	-12
gen	body	-18	-16	-12
gen	head	-18	-24	-13
gen	hand left	-31	-24	-1
gen	hand right	-13	-24	-1
gen	foot right	-18	-24	-12

running lowpolygame :
-----------------------------


SHADER ERROR
3DreamEngine/shaders/blur_cube.glsl
Error validating pixel shader:

ERROR: 0:13: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 1 compilation errors.  No code generated.



stack traceback:
	3DreamEngine/shader.lua:23: in function 'newShader'
	3DreamEngine/shader.lua:77: in main chunk
	[C]: in function 'require'
	3DreamEngine/init.lua:31: in main chunk
	[C]: in function 'require'
	examples/knight/main.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:74: in function 'draw'
	[string "boot.lua"]:618: in function <[string "boot.lua"]:594>
	[C]: in function 'xpcall'
	[string "boot.lua"]:802: in function <[string "boot.lua"]:769>

shader simple is not designed for mesh type textured!
shader simple is not designed for mesh type textured!
transform	0	1	0	4484
group	1	6
transform	2	3	22	4572
shape	3
transform	4	5	17	4683
shape	5
transform	6	7	17	4789
shape	7
transform	8	9	22	4895
shape	9
transform	10	11	23	5007
shape	11
transform	12	13	23	5118
shape	13
gen	foot left	-18	-24	-12
gen	body	-18	-16	-12
gen	head	-18	-24	-13
gen	hand left	-31	-24	-1
gen	hand right	-13	-24	-1
gen	foot right	-18	-24	-12

Monkey example:
-----------------------
SHADER ERROR
3DreamEngine/shaders/blur_cube.glsl
Error validating pixel shader:

ERROR: 0:13: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 1 compilation errors.  No code generated.



stack traceback:
	3DreamEngine/shader.lua:23: in function 'newShader'
	3DreamEngine/shader.lua:77: in main chunk
	[C]: in function 'require'
	3DreamEngine/init.lua:31: in main chunk
	[C]: in function 'require'
	examples/monkey/main.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:74: in function 'draw'
	[string "boot.lua"]:618: in function <[string "boot.lua"]:594>
	[C]: in function 'xpcall'
	[string "boot.lua"]:802: in function <[string "boot.lua"]:769>


shader simple is not designed for mesh type textured!
shader simple is not designed for mesh type textured!

and particle system example:
----------------------------------------

SHADER ERROR
3DreamEngine/shaders/blur_cube.glsl
Error validating pixel shader:

ERROR: 0:13: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 1 compilation errors.  No code generated.



stack traceback:
	3DreamEngine/shader.lua:23: in function 'newShader'
	3DreamEngine/shader.lua:77: in main chunk
	[C]: in function 'require'
	3DreamEngine/init.lua:31: in main chunk
	[C]: in function 'require'
	examples/particlesystem/main.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:74: in function 'draw'
	[string "boot.lua"]:618: in function <[string "boot.lua"]:594>
	[C]: in function 'xpcall'
	[string "boot.lua"]:802: in function <[string "boot.lua"]:769>


shader simple is not designed for mesh type textured!
shader simple is not designed for mesh type textured!
Branch: 17220 particle-faces
Branch: 17958 particle-faces
Grass: 11838 particle-faces
Grass: 1674 particle-faces
Branch: 14145 particle-faces
Branch: 18081 particle-faces

**Comment by giovifav** [comment]
the monkey example white dream.sky_as_reflection = false seems running fine with this console output:

SHADER ERROR
3DreamEngine/shaders/blur_cube.glsl
Error validating pixel shader:

ERROR: 0:13: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 1 compilation errors.  No code generated.

stack traceback:
	3DreamEngine/shader.lua:23: in function 'newShader'
	3DreamEngine/shader.lua:77: in main chunk
	[C]: in function 'require'
	3DreamEngine/init.lua:31: in main chunk
	[C]: in function 'require'
	examples/monkey/main.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:74: in function 'draw'
	[string "boot.lua"]:618: in function <[string "boot.lua"]:594>
	[C]: in function 'xpcall'
	[string "boot.lua"]:802: in function <[string "boot.lua"]:769>


shader simple is not designed for mesh type textured!
shader simple is not designed for mesh type textured!


Edit:
-------

i have add dream.sky_as_reflection = false to love.draw on each example and all seems working but a they are a bit dark

**Comment by Luke100000** [comment]
The Tavern demo uses 9 fully smooth shadowed cube lights, its (unrealistic) heavy. Press B to disable the smooth shadows.
`sky_as_reflection = false` should fall back to a default color, which in most cases should be even brighter :thinking: But its a great start on finding the error, thank you!
The latest commit removed the blur error and the two last lines. Should not be the main problem but its fixed now.

**Comment by giovifav** [comment]
You are welcome.
I'm a newbie in game development but i'm  trying to figure out if i can convert my little top-down  tower defense game into something 3d and more polish and your engine seem them best option (i really don't want to change my codebase to another framework than love2d).
Keep you motivated on this project because it is  can be a game changer to how powerful love2d is perceive.
