### ISSUE TITLE
Can't add new argument to function

### ISSUE THREAD

**Issue by borsuczyna** [3dreamengine/3DreamEngine#34]
If I add argument to function c:collide its ignored by function (nil) and please add in collide function triangles check maximum distance for better performance :)

**Comment by Luke100000** [comment]
> If I add argument to function c:collide its ignored by function (nil)
What types of collider are you trying to collide?

> please add in collide function triangles check maximum distance for better performance
Already implemented. Meshes/Triangles are put into groups and groups are tested using fast spherical checks before.
