### ISSUE TITLE
An error occurs if no textures added to *.mat file

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#36]
Error: 3DreamEngine/loader.lua:863: bad argument #11 to 'setVertex' (number expected, got table)
stack traceback:
        [string "boot.lua"]:777: in function <[string "boot.lua"]:773>
        [C]: in function 'setVertex'
        3DreamEngine/loader.lua:863: in function 'createMesh'
        3DreamEngine/loader.lua:657: in function 'loadObject'

Adding any texture to a mat file (tex_albedo, tex_normal, etc) solves the problem.

**Comment by Luke100000** [comment]
Errored because emission is a table, which was unexpected when using the non-texture shader in your version. It should have been fixed already. Does it work? Sorry for the rather big changes in the API, there was too much mess :P
