### ISSUE TITLE
New wind shader (or it's controls) makes ugly artifacts

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#39]
https://github.com/thisnickwasfree/3dreamengine_tests
demo3 and demo4 at the link.
In complete scene everything is much worse.
Look at the corrupted textures at the trees:
https://ibb.co/D4W9jsf][img]https://i.ibb.co/G7pWrBQ/2020-10-24-132235-1920x1080-scrot.png
And in realtime they changes their look several times per second.

**Comment by Luke100000** [comment]
Thats not the shader :)
You made a double-sided mesh (in the .obj). Those are necessary if using an engine which can not toggle/disable the cullMode, but 3Dream can, and you do. So you are drawing both sides, which cause Z-fighting. Go into the .obj and delete one side. Or in the material delete cullMode but I prefer option 1 for performance reasons.

**Comment by thisnickwasfree** [comment]
And does 3Dream engine support double-sided (I mean visible/renderable from both sides of polygon's normal) materials?
Cause this tree is a lod from SpeedTree, it consists from flat «boxes» not planes to be visivle from any side. I can easily remade the model, but problems with visibility from some angles will appear.

**Comment by Luke100000** [comment]
Sure, `cullMode = "none"` (or its setter material:setCullMode(mode)) in the material overwrites the used cullmode, where none just disables it. For most objects this is unwanted, so the default is "back", but most foliage require this. Or you can use double sided, but not in combination with "none". Also its slower. Don't use it. If possible. SpeedTree surely has an option for this.
