### ISSUE TITLE
Double-star solar system

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#42]
https://i.ibb.co/GHmQkXr/2020-10-24-205007-1920x1080-scrot.png

Looks nice, but a bit strange.

**Comment by Luke100000** [comment]
Wha? How did you made this XD

**Comment by thisnickwasfree** [comment]
I do not know. Looks like the blue «sun» is some kind of reflection at the sky dome. It moves synchronously with the sun, but in front of it. Sometimes it's bigger than the sun (at the higher part of trajectory).

**Comment by Luke100000** [comment]
Hmm. Well, fog simulates light anisotropy, but a) fog seems disabled and b) why offset? Well, I try to reconstruct this error...
