### ISSUE TITLE
Camera controls work strange

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#43]
I have only default canera in the scene. All methods like
dream.setFov (45);
dream:setNear (1);
dream:setFar (100);
do not work (nil).
But I can use 
dream.cam.fov = 45;
dream.cam.near = 1;
dream.cam.far = 100;

**Comment by Luke100000** [comment]
Because those functions work on the camera object, not dream. Use `dream.cam:setFov()` instead. I added setter/getter to most objects since thats more professional, and some setter perform additional error checking and math.
