### ISSUE TITLE
Clouds enabling/disabling

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#44]
There are some clouds at screenshot, right? They are moving…
But I have these in my scene: dream:setClouds(false)
So, how does enabling/disabling of clouds work
https://ibb.co/0tjhT0L

**Comment by Luke100000** [comment]
This is the second layer, a static HDRI map. I forgot about those.

**Comment by Luke100000** [comment]
Next commits will contain a function `dream.setUpperClouds` to control those.
