### ISSUE TITLE
Sun direction

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#46]
looks like dream:setSunDir(direction) does not affect sun trajectory.
I've used different values with no result.
Is it possible to turn sun's trajectory at 90° somehow? Through setSunDir or some kind of setNorth function?

**Comment by Luke100000** [comment]
`setSunDir` is messing with `setDaytime`, switch those lines to they overwrite correctly. Setting the suns orientation is currently not popssible. Do you need it?

**Comment by thisnickwasfree** [comment]
That  ll be useful to have control on sun's way at sky dome. North can be at any direction during level development, and remaking of the whole map sometimes not an option.

**Comment by Luke100000** [comment]
next commit will contain an additional argument in `setSunOffset` which allows you to set the rotation.
