### ISSUE TITLE
Transparent textures broken with last update

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#47]
https://ibb.co/rsC70v4

**Comment by Luke100000** [comment]
Not broken, part of the GPU improvements. I told you that there were things a GPU hate, and it makes things more complicated. Discard, a command required by the trees for example, is slow. `material.discard = true` or `material.alpha = true` fixes this, in your case the first one is the right one. I could enable this by default, but it slows down performance a bit. What do you think? Is it worth the ~3-5% slowdown, or -25% slowdown on direct render mode?

I understand that this is strange, but most engines for example have a transparency texture separated from the color tex, so they recognize if alpha is possible. I support merged textures and have no chance to detect if alpha is present. Thats why I need the discard value.

**Comment by thisnickwasfree** [comment]
Well… I think that it should be in docs; key word «transparency». Which variant is default is not important. The question: are material.discard = true or material.alpha = true for a few models (and can be set in *.mat, for example) or for the whole scene?

**Comment by Luke100000** [comment]
just the models that are affected.
It has semi alpha? (transparency 0.5, ...) -> material.alpha = true (sets discard too since required)
It has full alpha or none alpha? -> material.discard = true only
It has no alpha at all? Don't change anything.

I will update the docu to make this more clear.
