### ISSUE TITLE
setDefaultShaderType issue

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#49]
Error: 3DreamEngine/functions.lua:81: attempt to index local 'uv2' (a nil value)
stack traceback:
        [string "boot.lua"]:777: in function '__index'
        3DreamEngine/functions.lua:81: in function 'calcTangents'
        3DreamEngine/loader.lua:370: in function 'createMesh'
        3DreamEngine/loader.lua:293: in function 'loadObject'

dream:setDefaultShaderType("Phong") gives this error with some objects.
dream:setDefaultShaderType("PBR") gives this error with some too.

BTW, print ("SHADER:",dream:getDefaultShaderType()) prints nil.
Or false after dream:setDefaultShaderType(false), dream:setDefaultShaderType(Phong), dream:setDefaultShaderType(phong) — I've checked several variants, sending strings and possible vars.

In old version phong shader works fine with this object.
UP: fine while mtl presented, not mat.

UP2: merging of dup-vetexes and re-unwraping fixes the model, so new version of engine is able to load it.

**Comment by Luke100000** [comment]
This errors seems like a missing UV map, therefore the unwrap helped. I will add support for missing uvs. But I wonder why the old version was able to load it...

**Comment by Luke100000** [comment]
```
dream:setDefaultShaderType("Phong")
print(dream:getDefaultShaderType()) --> prints phong
```
I can not reconstruct the error. Nil means, it never has been set and it tries to set automatically Phong or simple (which is a untextured Phong). By default you do not need to set this value yourself, unless you are using custom base shaders or the PBR one.

**Comment by thisnickwasfree** [comment]
>But I wonder why the old version was able to load it...

only with *.mtl.

>I can not reconstruct the error. 

dream:setDefaultShaderType("Phong") with obj containing incorrect uv data and mat (not mtl) gives error.
But without using setDefaultShaderType (some_shader) scene loads, but shows nil as DefaultShaderTypeValue. But looks like it uses this shader anyway — I see no differ in the picture.
If I'll catch this issue again, I'll make a demo.

**Comment by Luke100000** [comment]
Probably because without the default is uses simple (no texture), which does not require uvs. But settings default forces the use of textured Phong. Anyways, that has to be fixed.
And you see no difference because it technically is the same shader, just slower (because it uses a white default texture). I use it for low poly scenes without texture.
