### ISSUE TITLE
About fixing camera's far plane…

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#50]
Wrong direction: it worse now.
100m far, artifacts appear after smooth camera direction (to 90°, for example).
https://ibb.co/VMnD2BK

**Comment by Luke100000** [comment]
stop doing that to my engine XD May I ask what you set for the near plane?

**Comment by thisnickwasfree** [comment]
>May I ask what you set for the near plane?

dream.cam.near = 1;

**Comment by Luke100000** [comment]
Yea, thats a problem. Because I do not fully understand the math yet 1 is too big. The same problem with far, just with the near plane :P

I'll fix that. Use 0.5 or something for now. (1.0 is rather big btw)
