### ISSUE TITLE
dream:resetLight(true) issue

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#51]
dream:resetLight(true) in the scene with sun gives this error:

Error: 3DreamEngine/shaders/base/Phong.lua:151: Shader uniform 'tex_normal' does not exist.
A common error is to define but not use the variable.
stack traceback:
        [string "boot.lua"]:777: in function <[string "boot.lua"]:773>
        [C]: in function 'send'
        3DreamEngine/shaders/base/Phong.lua:151: in function 'perMaterial'
        3DreamEngine/render.lua:262: in function 'render'
        3DreamEngine/render.lua:527: in function 'renderFull'
        3DreamEngine/render.lua:714: in function 'present'

dream:resetLight(false) works. Important moment: I use dream:present(false, false, true).

**Comment by Luke100000** [comment]
Thanks, will be fixed soon. I assume you used ambient color only (no reflection) and no light sources? This combination causes the problem.

**Comment by thisnickwasfree** [comment]
No lights, no reflections, yes.
