### ISSUE TITLE
setFrustumCheck documentation and plane issues

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#52]
setFrustumCheck now use string not bool, but documentation says nothing about this.
"fast" works fine, but "plane" is too aggressive (removes tiles at the edges of screen).

**Comment by Luke100000** [comment]
whoops, my bad. Thanks. Plane mode is WIP. Plane is the more common solution (implemented in most games, ...), more accurate, less GPU usage at a slightly increased CPU usage. I am pretty sure I did the math right, still, as you confirmed, it doesn't work. I will look into this somewhere in the future, but for now the fast one does its job.

**Comment by Luke100000** [comment]
removed fast frustum culling and fixed the plane based one in the beta branch, commit #2829b6a6, will merge soon
