### ISSUE TITLE
Fast in frustum function

### ISSUE THREAD

**Issue by thisnickwasfree** [3dreamengine/3DreamEngine#6]
Any chances to get fast "in frustum" function to draw only those meshes which in camera's fow?
I can check it in love.draw, but it slows down the scene (25 vs ~115 fps). But! The same mechanism gives 165 Vs 140 fps while watching to the area where no meshes placed.

**Comment by thisnickwasfree** [comment]
dream.sun_shadow = false 
dream.sun_shadow = false 

But there is a shadow on the screenshot:

[](https://ibb.co/Ryfgw5G)

**Comment by Luke100000** [comment]
Feature in todo, together with LODs. I expected a lower FPS yield, thanks for the benchmark.

**Comment by Luke100000** [comment]
Implemented. Not perfectly but it works. Dream.frustumCheck (default true) can toggle it.
Manual usage is not necessary, but the function would be:
```
--cam (e.g. the default cam dream.cam)
--pos is the center of the object to check
--size is the radius
dream:inFrustum(cam, pos, size)
```
