### ISSUE TITLE
vec2 and vec3 in global environment.

### ISSUE THREAD

**Issue by FatalistError** [3dreamengine/3DreamEngine#61]
The issue is simple, I don't want 3dreamengine's vec2 and vec3 libraries, and I carefully picked my own math library. However, for some reason, 3dreamengine's already reserves vec2, vec3 (and probably mat4) for _IT'S OWN_ libraries, which is utterly ridiculous. 

The solution is simple, 3dreamengine should use local variables and or a table. I shouldn't have to declare a local variable in LITERALLY EVERY SINGLE FILE to use my math libraries without breaking dream engines libraries.

This is a very intrusive problem in my opinion.

**Comment by flamendless** [comment]
You can make a PR to fix that

**Comment by FatalistError** [comment]
> You can make a PR to fix that

I could, but I also really am not in the mood to go through an entire 3d renderer fixing every file because somebody didn't think about the implications of loading additional libraries for the _entire_ environment. I have my own stuff to do, and I'd rather spend my free time working on my own projects instead of fixing other peoples, sorry.

**Comment by FatalistError** [comment]
issues shouldn't be discarded simply because "you could fix it yourself" I don't think that's a good way of approaching problems, ever.

**Comment by Luke100000** [comment]
As I also mentioned in Discord, with your current tone I have especially low interest in fixing that anytime soon.

**Comment by flamendless** [comment]
I agree with the author of this project. You are free to use this amazing open-source project at your volition, if you find something you don't agree with, fork it and make your desired changes

**Comment by Luke100000** [comment]
Added in beta
