### ISSUE TITLE
Objects start to disappear after few minutes

### ISSUE THREAD

**Issue by kikonen** [3dreamengine/3DreamEngine#67]
Not sure why, but objects start to disappear from screen after few minutes

i.e. rather simple sample app
- https://github.com/kikonen/love-test
- tag: bug_disappearing_objects
- 
Just running it  and wair few minutes, walls, and balls start to disappear.

Tried,
- removed "push"
- removed "cameraController"
- remove everything else than "dream:" calls from draw
No change in behaviour in any trials

GPU
- Intel Iris Plus Graphics, i7-1065G7
- 

Notices,
- Objects are not completely gone, realized that if moving camera around, then they appear, sometimes.
- "dream:setFrustumCheck(false)" did not affect behaviour so not related to that then either
-

**Comment by kikonen** [comment]
what it is must be some problem in my sample

**Comment by kikonen** [comment]
*NOTE*
Managed to reproduce similar "objects start to disappear" with "examples/firstpersongame", had that demo running for a while (not tens of minutes, minutes, EDIT, too my watch, and measured, around 3 min point, objects started to disappear) and objects started to disappear.

=> Since no my own logic on that, issue must be a bit more generic.

**Comment by kikonen** [comment]
**NOTE**
Based into info what I got in LÖVE forum (https://love2d.org/forums/viewtopic.php?t=95061) this might be issue with love 11.4, which should get fixed in LÄVE 11.5. Doing test trials with LÖVE 11.5 (compile from HEAD of main) to verify this.

**Comment by ttmso** [comment]
im having the same error but on my own project in 3de

**Comment by kikonen** [comment]
@LucasAiden I suggest compiling LÖVE from the github master, and trying with it, if you're in windows, I've precompiled binary you can use to verify if it's same thing

You may try with this,
https://www.ikari.fi/share/love-11-beta.zip

**Comment by ttmso** [comment]
I tried it.

11.4 started to break at 115 seconds.
11.5 after 180 seconds it still worked fine

So it worked.

**Comment by kikonen** [comment]
Oh yes, I seemingly forgot to report my results also here (did it in LÖVE forum only seemingly). Using LÖVE 11.5 built from master HEAD in git repo of love, fixed it for me. Haven't seen problem and have been running with 11.5a for few weeks now

With 11.4 my app started getting random failures within 5 sec to few mins from 3dream.

**Comment by ttmso** [comment]
Also can you send a version with lovec.exe? thanks.

**Comment by kikonen** [comment]
You may try this, tried to compile also lovec,

https://www.ikari.fi/share/love-11-beta–20231124.zip

**Comment by ttmso** [comment]
It works

**Comment by kikonen** [comment]
LÖVE 11.5 released, thus can close this

https://love2d.org/forums/viewtopic.php?t=95265&start=10
